sudo: require

services:
  - docker

before_install:
  - docker build -t poyori007/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true poyori007/react-test npm test

after_success:
  - docker build -t poyori007/multi-client ./client
  - docker build -t poyori007/multi-nginx ./nginx
  - docker build -t poyori007/multi-server ./server
  - docker build -t poyori007/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push poyori007/multi-client
  - docker push poyori007/multi-nginx
  - docker push poyori007/multi-server
  - docker push poyori007/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: $AWS_APP
  env: $AWS_ENV
  bucket_name: elasticbeanstalk-us-east-2-467223906842
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY